# Generated by Django 5.2.6 on 2025-09-13 23:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('card_number', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13)])),
                ('full_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorization_document', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCard.parkingcard')),
            ],
        ),
        migrations.AddField(
            model_name='parkingcard',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiCard.user'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('car_plate', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('brand', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCard.parkingcard')),
            ],
        ),
    ]
